Bump Google client to get newer version of Guava
The previous version depended on an old version of Guava that would occasionally be selected over the newer version by projects depending on Panda, causing  mayhem with NoSuchMethodErrors and things. This version depends on Guava 22.0 which seems to be new enough not to cause problems